{"error": "bounds are inconsistent with p=[1.000000953675226]", "traceback": "Traceback (most recent call last):\n  File \"run_regression_tests.py\", line 66, in optimize_random_skater\n    best_r, best_val, info = optimal_r(f=f, y=brownian_with_exogenous(n=n), k=k,a=None,t=None, e=None,\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/skaters/optimization.py\", line 38, in optimal_r\n    best_val, best_rn, feval_count = optimizer(objective, n_trials=n_trials, n_dim=n_dim, with_count=True)\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/optimizers/swarmlibcube.py\", line 120, in swarmlib_pso_cube\n    return swarmlib_cube(objective=objective, n_trials=n_trials, n_dim=n_dim, with_count=with_count, algo='pso')\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/optimizers/swarmlibcube.py\", line 113, in swarmlib_cube\n    best_particle = problem.solve()\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/optimizers/swarmlibcube.py\", line 74, in solve\n    particle.step(global_best_particle.position)\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/swarmlib/pso/particle.py\", line 52, in step\n    self._position = self._position + self.__velocity\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/swarmlib/util/coordinate.py\", line 56, in _position\n    self.__value = self._function(self.__position)\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/optimizers/swarmlibcube.py\", line 107, in cube_objective\n    return objective(un)\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/skaters/optimization.py\", line 29, in objective\n    r = from_space(u)\n  File \"/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/timemachines/skaters/conventions.py\", line 180, in from_space\n    assert 0 <= u <= 1, \"bounds are inconsistent with p=\" + str(ps)\nAssertionError: bounds are inconsistent with p=[1.000000953675226]\n"}